name: backend Build and Deploy

on:
  push:
    branches:
      - main 
env:
  REGISTRY: ghcr.io
  OWNER: $(echo ${{github.repository}} | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')
  IMAGE_NAME: $(echo ${{github.repository}} | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
  TAG: $(cat version.txt)-$(echo ${{github.sha}} | tail -c 8)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm install
    - name: Lint code
      run: |
        npm run lint
    - name: Run tests
      run: |
        npm run test
    - name: Create build
      run: |
        npm run build
    - name: Build Docker image
      run: |
        docker build -t ${{env.IMAGE_NAME}} .
    - name: Login to GHCR
      run: |
        echo ${{secrets.GITHUB_TOKEN}} | docker login ${{env.REGISTRY}} -u ${{env.OWNER}} --password-stdin >/dev/null 2>&1
    
    - name: Push Docker Image
      run: |
        docker tag ${{env.IMAGE_NAME}} ${{env.REGISTRY}}/${{env.OWNER}}/${{env.IMAGE_NAME}}:${{env.TAG}}
        docker push ${{env.REGISTRY}}/${{env.OWNER}}/${{env.IMAGE_NAME}}:${{env.TAG}}

# name: Release 
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main
# jobs:
#   # deploy:
#   #   runs-on: ubuntu-latest
#   #   steps:
#   #     - name: Get Code
#   #       uses: actions/checkout@v3
#   #     - name: Building the Images
#   #       run: docker build . -t dilipsingh27/k8s-backend
#   #     - name: Logging into the DockerHub 
#   #       run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
#   #     - name: Pushing the images to dockerhub repository
#   #       run: docker push dilipsingh27/k8s-backend
#   docker:
#     runs-on: ubuntu-latest
#     env:
#       REGISTRY: ghcr.io
#       USER: $(echo ${{github.repository}} | cut -d'/' -f1 | tr '[:upper:]' '[:lower:]')
#       IMAGE_NAME: $(echo ${{github.repository}} | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
#       TAG: $(cat version.txt)-$(echo ${{github.sha}} | tail -c 8)

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install dependencies
#         run: |
#           npm install
#       - name: Lint code
#         run: |
#           npm run lint
#       - name: Run tests
#         run: |
#           npm run test
#       - name: Create build
#         run: |
#           npm run build

#       - name: Build Docker Image 
#         run: |
#           docker build -t ${{env.IMAGE_NAME}} .

#       - name: Login to ghcr
#         run: |
#           echo ${{secrets.GITHUB_TOKEN}} | docker login $REGISTRY -u $USER --password-stdin >/dev/null 2>&1
#       - name: Push docker image
#         run: |
#           docker tag $IMAGE_NAME ${{env.REGISTRY}}/$USER/$IMAGE_NAME:$TAG
#           docker push ${{env.REGISTRY}}/$USER/$IMAGE_NAME:$TAG