name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get Code
  #       uses: actions/checkout@v3
  #     - name: Building the Images
  #       run: docker build . -t dilipsingh27/k8s-backend
  #     - name: Logging into the DockerHub 
  #       run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
  #     - name: Pushing the images to dockerhub repository
  #       run: docker push dilipsingh27/k8s-backend
  docker:
    runs-on: ubuntu-latest
    env:
      TAG: dockert
      PAT: ${{ secrets.GIT_TOKEN}}
      USER: dilipsingh27
      REGISTRY: ghcr.io
      VERSION: v1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t $TAG .

      - name: Login to ghcr
        run: |
          echo $PAT | docker login ghcr.io -u $USER --password-stdin
          docker tag $TAG ${{env.REGISTRY}}/$USER/$TAG:latest
          docker push ${{env.REGISTRY}}/$USER/$TAG:${{ env.VERSION }}
